/*
 * ofxLlamaCpp
 *
 * Copyright (c) 2025 Yannick Hofmann
 * <contact@yannickhofmann.de>
 *
 * BSD Simplified License.
 * For information on usage and redistribution, and for a DISCLAIMER OF ALL
 * WARRANTIES, see the file, "LICENSE.txt," in this distribution.
 */
 
#pragma once

#include "ofMain.h"
#include "ofxLlamaCpp.h"

// This is the main application class that inherits from ofBaseApp.
// It encapsulates the application's logic and handles setup, updates, and drawing.
class ofApp : public ofBaseApp {
public:
    // setup() is called once when the application starts.
    // It's used for initializing variables, loading assets, and setting up the environment.
    void setup();

    // update() is called repeatedly in a loop.
    // It's used for updating the application's state, such as animations or data processing.
    void update();

    // draw() is called repeatedly after each update().
    // It's used for rendering visuals to the screen.
    void draw();

private:
    // An instance of the ofxLlamaCpp class, which provides the core functionality for interacting with the Llama model.
    ofxLlamaCpp llama;

    // A string to store the output generated by the Llama model.
    std::string output;

    // A boolean flag to indicate whether the Llama model has been successfully loaded.
    bool modelLoaded;

    // A string to store the input prompt that will be sent to the Llama model.
    std::string prompt;

    // A helper function to wrap long strings of text to fit within a specified width.
    // This is useful for displaying text neatly on the screen.
    std::string wrapString(std::string text, int width);

    // A helper function to check if a given string starts with a specific prefix.
    bool startsWith(const std::string& text, const std::string& prefix);
};
